### PR TITLE
Remove those constructs deprecated for Unihan

### PR DESCRIPTION
**Pull request by sydb**
I _think_ I have this right. See #1805.
I wanted to ask @duncdrum to review, but he was not in the drop-down list of possibilities.
I made this high priority since the build is at least messed up, if not broken, until these deprecations are removed.

### CODE REVIEW

**Review by duncdrum — APPROVED** [review]
Hi Syd,  

Looks good to me.

**Comment by sydb** [comment]
Thank you, @duncdrum !

**Comment by martindholmes** [comment]
This might be a bit of a pain, but I think I'd like to see a full build and Guidelines output from this, since the changes are so significant. I've set up a build job to see what happens:\

https://teijenkins.hcmc.uvic.ca/job/TEI-P5-sydb_uniHan_deprecations_of_2022-02-15/

**Comment by sydb** [comment]
> I think I'd like to see a full build and Guidelines output from this, since the changes are so significant

Makes perfect sense to me. I do not understand why you would want Mr. Jenkins to build it rather than build it yourself, but I also don’t care.

[BTW, _my_ local build worked fine, both in docker and just local. The Deprecations page looks a bit silly, as there is nothing on it, but other than that a quick once-over said it looked fine.]

**Comment by martindholmes** [comment]
@sydb The build failed, at the nvdl stage; take a look at the errors. I don't think you run the nvdl stuff locally, do you? There seem to be things in the Exemplars that need fixing.

**Comment by sydb** [comment]
Egads, no — it did _not_ build OK for me. (I do not use `nvdl` in a local build, but do via Docker.) But that was not the problem, I don’t think. I am pretty confident I simply screwed up and was looking at the output of the wrong validation process. Sorry. (And thanks for catching!)
I have a few minutes now to take a look …

**Comment by sydb** [comment]
Fixed, I hope, at 94dac19e4.

**Comment by martindholmes** [comment]
Building again on Jenkins now...

**Comment by sydb** [comment]
Mr. Travis is happy.

**Comment by martindholmes** [comment]
Mr Jenkins too. @duncdrum would you mind reading through this?

https://teijenkins.hcmc.uvic.ca/job/TEI-P5-sydb_uniHan_deprecations_of_2022-02-15/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/WD.html

It looks OK to me, but a second pair of eyes would be good.

**Comment by sydb** [comment]
Note, though, @martindholmes, that there have been no changes to WD (except to remove the XIncludes of the now defunct elements). It has described use of `<unicodeProp>`, `<unihanProp>`, and `<localProp>` since summer 2019.

**Comment by duncdrum** [comment]
@martindholmes yup looks good to me, I would suggest to have a look into manual updating Unicode to the latest and greatest right now. I still wasn't able to complete the automated update for phase 5 on CI.

**Comment by martindholmes** [comment]
@duncdrum Do we have documentation on how to update to the latest Unicode?

**Comment by martindholmes** [comment]
@sydb @martinascholger I don't know what needs to be done to update the Unicode stuff, but since the build is already broken by the expired deprecations, I would recommend merging this PR and raising a separate issue for the updates to Unicode. That issue should also specify that documentation should be created for how to do it. Calling out to @martinascholger to make a final decision on merging.

After this PR is merged, we'll have to do the p5subset and fallout fixes in the Stylesheets repo too, before all is well again.

**Comment by sydb** [comment]
I agree with @martindholmes and think this PR should be merged urgently.

**Comment by duncdrum** [comment]
@martindholmes The query files should be in the repo, but I don’t think I finished documentation. Where should that go btw.

**Comment by martindholmes** [comment]
@duncdrum I'm not sure where the documentation should go. @sydb, what's the current Council practice here? Should it be a TCW?

**Comment by martinascholger** [comment]
Looks good to me. Will do the merge now. 
@martindholmes -- yes, I think this should be a TCW

**Pull request merged**
