### PR TITLE
inconsistent wording of attr classes 2142

### PR DESCRIPTION
**Pull request by martinascholger**
This PR adresses #2142. I've changed the descriptions to plurals. In addition I've changed descriptions where the attributes were listed in the `<desc>` element, and I replaced 'supplies' with 'provides'.

### CODE REVIEW

**Review by sydb — APPROVED** [review]
Looks OK to me (see below). Passes my local TEI build. Would not surprise me if some expected results in Stylesheets tests need to be updated when we port this over to that repo. (Which makes me think we should do so soon.)
### below
~~~
*** /tmp/classes_1_attr_descs_dev.txt	2021-08-22 16:49:35.721400551 -0400
--- /tmp/classes_1_attr_descs_2142.txt	2021-08-22 16:49:01.233684394 -0400
***************
*** 3,5 ****
! provides an attribute to indicate the hand in which the content of an element was written in the source being transcribed.
! provides an attribute to indicate whether or not the element concerned is considered to mark the end of an orthographic token in the same way as whitespace.
! provides an attribute which may be used to supply a canonical reference as a means of identifying the target of a pointer.
--- 3,5 ----
! provides attributes to indicate the hand in which the content of an element was written in the source being transcribed.
! provides attributes to indicate whether or not the element concerned is considered to mark the end of an orthographic token in the same way as whitespace.
! provides attributes which may be used to supply a canonical reference as a means of identifying the target of a pointer.
***************
*** 8 ****
! provides an attribute for representing fragmentation of a structural element, typically as a consequence of some overlapping hierarchy.
--- 8 ----
! provides attributes for representing fragmentation of a structural element, typically as a consequence of some overlapping hierarchy.
***************
*** 11 ****
! provides an attribute used by elements to point to an external source.
--- 11 ----
! provides attributes used by elements to point to an external source.
***************
*** 15,16 ****
! provides an attribute to indicate the type of section which is changing at a specific milestone.
! provides an attribute to indicate any specialised notation used for element content.
--- 15,16 ----
! provides attributes to indicate the type of section which is changing at a specific milestone.
! provides attributes to indicate any specialised notation used for element content.
***************
*** 23,24 ****
! provides an attribute which may be used to indicate enjambement of the parent element.
! provides an attribute used to distinguish different styles of dictionary entries.
--- 23,24 ----
! provides attributes which may be used to indicate enjambement of the parent element.
! provides attributes used to distinguish different styles of dictionary entries.
***************
*** 27 ****
! provides an attribute to indicate text type or classification.
--- 27 ----
! provides attributes to indicate text type or classification.
***************
*** 29 ****
! supplies the change attribute, allowing its member elements to specify one or more states or revision campaigns with which they are associated.
--- 29 ----
! provides attributes allowing its member elements to specify one or more states or revision campaigns with which they are associated.
***************
*** 31 ****
! supplies the attribute used to identify the witnesses supporting a particular reading in a critical apparatus.
--- 31 ----
! provides attributes used to identify the witnesses supporting a particular reading in a critical apparatus.
***************
*** 38 ****
! provides an attribute indicating the target namespace for an object being created
--- 38 ----
! provides attributes indicating the target namespace for an object being created
~~~

**Comment by sydb** [comment]
This is a pretty trivial change and has been reviewed positively. If anyone else could take a look and (if OK) push the button by Sat 28 Aug, that would be good.

**Comment by ebeshero** [comment]
@sydb @martinascholger Looks good. I’m going to patch through a tiny but significant set of corrections of “that” for “which” in several of these, since the clauses are for defining and are “restrictive”. 

 (See https://www.grammarly.com/blog/which-vs-that/ and
https://owl.purdue.edu/owl/general_writing/grammar/that_vs_which.html )

Where we have: “provides attributes which do yada yada”

we’d revise to:

“provides attributes that do yada yada”.

**Comment by lb42** [comment]
Fwiw, this is a br/us usage difference. I quote: In British English,, ‘that’ and ‘which’ can both be used for restrictive clauses, allowing for a bit more flexibility. But in both the US and the UK, non-restrictive clauses are only written with ‘which’.

Reluctantly using Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ebeshero** [comment]
Ah, that explains a lot, @lb42 . But the same source you’re quoting says, “ If you want to avoid confusion, use ‘that’ for restrictive clauses and ‘which’ for non-restrictive clauses. ” It’s funny to find an American usage that is more strict than British, but I blame generations of English teachers drilling this into our heads.

**Comment by ebeshero** [comment]
Not that anyone would seriously be confused here. It looked a little funny to me, though, so I suppose other members of the American English subset of the TEI community (or the set of those who spent time marking student papers) might wonder a bit. We could easily leave it alone. But I suspect it’s marginally better to use “that”.

**Comment by sydb** [comment]
I am inclined to agree you, @ebeshero, because en-GB allows for either.

(The overall policy, IIRC, is to try to avoid cases in which en-US and en-GB disagree, and to use en-GB when such a case is unavoidable. But in this case we can find wording in which the two agree, so I think we should use that.)

**Comment by ebeshero** [comment]
@sydb Will do, later today or tomorrow AM at latest.

**Comment by sydb** [comment]
You have until Sat 28 for sure; some would say until Sun 29. :grinning:

**Comment by JanelleJenstad** [comment]
Looks good with the plurals. I'm happy with @ebeshero's revision of "which" to "that" in restrictive clauses, since American and Canadian English require "that" and British English allows "that."

**Comment by ebeshero** [comment]
@JanelleJenstad Uh oh! I had not made the “which” to “that” revisions yet! I am going to restore the branch for a moment until I finish it, and then merge it.

**Comment by ebeshero** [comment]
Please do NOT delete this branch just yet!

**Comment by ebeshero** [comment]
I'm not going to revert this merge. I think I can reopen the PR once I commit to the branch again, so I think we're okay.

**Comment by sydb** [comment]
I would not revert the merge unless you cannot avoid it. Just make the new changes to wording, no?
P.S. This change is trivial enough, if `git` is confusing, just do it in dev, IMHO.

**Comment by ebeshero** [comment]
Ah! Just saw this. Apparently, GitHub doesn't add changes to the same PR after it's been closed, so I wound up having to make a new PR because I was working in the branch. Since the change is so minor at this point, I'm just going to merge it into dev.

**Comment by JanelleJenstad** [comment]
I'm sorry! I did hesitate before deleting the branch but ended up trusting the GitHub message that it was okay to do so.

**Pull request merged**
