### PR TITLE
Constrain elementSpec based on Mode #1735

### PR DESCRIPTION
**Pull request by MegJBrown**
Implemented changes #1735

### CODE REVIEW

**Comment by sydb** [comment]
If _anyone_ can review this within the next, say, 18 hours …
It should be an easy review. 2 of the 3 files changed have a very trivial change (which is changing a content model snippet from `( valList | content )*` to `( valList | content )?`). The third change is just a new `<constraintSpec>`, and while the XPaths make use of sequence comparison and the `except` operator, they are not particularly gnarly. Pretty straightforward stuff.

**Review by martindholmes — COMMENTED** [review]
As far as I can see, this correctly implements the discussion on the ticket. The only thing that slightly bothers me is the word "incongruous" in the Schematron error message; I'm not sure how helpful that is, especially to a non-native speaker. Would it be better to explain why it's not workable?

**Comment by sydb** [comment]
I think it is a valid complaint — that “incongruous” may not be the best wording; but I have not come up with anything better. I came up with something worse: “does not make sense”.

Ideas welcomed.

**Comment by martindholmes** [comment]
@sydb Fair enough. I guess I was looking for "...incongruous because...", but it's difficult to write a single explanation that covers all violations of the rule.

**Comment by JanelleJenstad** [comment]
I don't like "incongruous" either, mainly because it doesn't tell the user what to do to fix the problem. Suggested wording:

"This elementSpec element has both a
          mode= of "delete" and child elements, which is incongruous" --> "This elementSpec element has a mode= of "delete" even though it has child elements. Change the mode= to "change" or remove the child elements."

**Comment by JanelleJenstad** [comment]
"This elementSpec element has a 
          mode= of "<sch:value-of select="@mode"/>", but does not have any child elements or schema-changing
          attributes, which is incongruous" --> "This elementSpec element has a 
          mode= of "<sch:value-of select="@mode"/>", but does not have any child elements or schema-changing
          attributes. Specify child elements and/or change the attributes, or change the ....."

**Review by JanelleJenstad — CHANGES_REQUESTED** [review]
Rework wording as suggested on ticket to avoid "incongruous."

**Comment by sydb** [comment]
Thank you, @JanelleJenstad. Changes made, checked in at 8c27b978c.
I was able to test Schematron on commandline, looks OK. For reasons I cannot explain, I cannot get tei_all.isosch to work in oXygen (23.1) at all, even after deleting all the children of `<schema>`. Will try to look at that a little more tomorrow.

**Review by ebeshero — APPROVED** [review]
This rewording looks good to me, as do the new Schematron constraints.

**Comment by sydb** [comment]
Tried to reproduce the problem described as an aside [above](#issuecomment-906030233) on a different machine, also running OXygen 23.1; problem did not occur.

**Pull request merged**
