### PR TITLE
issue deprecation warning when assertion is made without context

### PR DESCRIPTION
**Pull request by sydb**
Work on #2510.

Since this does not use the `@validUntil` deprecation mechanism, does it need to be added to Appendix G by hand?

I chose 2024-06-30 as end-of-deprecation date on my own accord. But since there is basically no difference between deprecation and error, here (although I suppose we could add role=warning), should we just go straight to error?

Anyway, it passes all tests on my local system both in & out of docker.

Reviewers: You will definitely want to ignore whitespace if you try comparing code. (Other than the code of `<constraintSpec>`, it is mostly a kinda pointless activity, IMHO.)

### CODE REVIEW

**Comment by sydb** [comment]
P.S. Since after this almost all Schematron was expressed with a namespace prefix (e.g., `<sch:assert>`) rather than an explicit namespace binding (e.g. `<assert xmlns="http://purl.oclc.org/dsdl/schematron">`), I changed the last few, as well. So now **all** Schematron in the Source/ directory uses namespace prefixes.

**Comment by martinascholger** [comment]
@martindholmes the tests are passing now, could you please have a look at it?

**Review by martindholmes — APPROVED** [review]
This looks good to me. But I really wish we could keep PRs to a single set of changes; this seems to be changing namespace mechanisms and whitespace as well as handling the `@context` problem. When there's so much change in one batch, it's really hard to review the PR. Could that be a recommendation somewhere?

**Comment by martinascholger** [comment]
Thanks @martindholmes for the quick review. You are right, different changes should not be tackled all at once.  We are trying to stick to our policy better.

**Pull request merged**
