### PR TITLE
allowing multiple seriesStmts in TEI Header for issue #1998

### PR DESCRIPTION
**Pull request by ebeshero**
Here's a fairly simple resolution to issue #1998, which I think should be ready for the upcoming 4.1.0 release. May I ask someone to review this and make sure it's okay to merge to dev?

### CODE REVIEW

**Review by martindholmes — COMMENTED** [review]
＠ebeshero Looks perfect to me!

**Comment by sydb** [comment]
Looks good to me, too. However, I am not fond of the use of the verb “applied” in HD:
> Multiple <seriesStmt> elements may be applied if …

I think “supplied” would be much better. Perhaps “used” or “encoded”.

**Comment by ebeshero** [comment]
@sydb Okay! I'll push that change now.

**Review by peterstadler — APPROVED** [review]
Looks good to me!

**Comment by lb42** [comment]
I haven't checked but presumably setiesStmt is now a member of att. Declarable?

Reluctantly using Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by peterstadler** [comment]
> I haven't checked but presumably setiesStmt is now a member of att. Declarable? 

Yes

**Review by hcayless — APPROVED** [review]
Looks good to me.

**Comment by lb42** [comment]
I just skimmed through the discussion on this ticket, and was a bit 
surprised by the implication that there might be sub-components of the 
TEI Header which were repeatable but were not members of att.declarable. 
Since the default assumption for any descriptive component of the header 
is that it concerns the whole of the associated text, I am finding it 
hard to think  of such a case.

However, that's no reason to disapprove of this proposed change.

**Review by martinascholger — APPROVED** [review]

**Pull request merged**
