### PR TITLE
Add unabbreviated name

### PR DESCRIPTION
**Pull request by rettinghaus**
Most abbreviated elements and attributes show their unabbreviated form in parentheses, `@decls` didn't. I suspect it stands for "declarations", so I added this one.

### CODE REVIEW

**Review by peterstadler — CHANGES_REQUESTED** [review]
Thanks for spotting! 
Technically this expanded form should go into a dedicated `<gloss>` element (without parentheses, but with corresponding `@xml:lang` and `@versionDate` attributes), not into the `<desc>`.

**Comment by rettinghaus** [comment]
Thanks for the hint! Changed it accordingly.

**Comment by peterstadler** [comment]
Help needed here from @TEIC/tei-technical-council : Is "declarations" the proper gloss for "decls"?

**Comment by lb42** [comment]
yes

**Review by peterstadler — APPROVED** [review]
No objections anymore :) 
Thanks @lb42 for confirming and @rettinghaus for the patience!

**Pull request merged**
