### PR TITLE
changed content model for content, #2381

### PR DESCRIPTION
**Pull request by martinascholger**
@HelenaSabel, @sydb, @martindholmes, @ebeshero: I know this is last minute. Maybe we can briefly discuss at the Stylesheets meeting if this should go into the upcoming release.

### CODE REVIEW

**Comment by sydb** [comment]
I think the only questions are “what breaks?” (apparently nothing tested by GitHub) and “does it need deprecation?”.

**Comment by peterstadler** [comment]
There's at least one example that should be updated: https://tei-c.org/Vault/P5/4.5.0/doc/tei-p5-doc/en/html/USE.html#index-egXML-d54e154070

**Comment by ebeshero** [comment]
We decided at Stylesheets meeting today that @sydb should draft a Schematron rule to issue a deprecation message, and then we'll plan to issue the changes to <content> in the next later (4.7.0) release. We will also update the prose <remarks> about wrapping several elements so this discusses the changes to Pure ODD as well as RELAX NG.

**Comment by sydb** [comment]
This PR should be handled in 2024-02 when the deprecation Schematron should also be removed. (And to handle it, just change the `<content>` of `<content>` to the following.)
~~~xml
 <content>
    <alternate>
      <elementRef key="valList" minOccurs="1" maxOccurs="1"/>
      <classRef key="model.contentPart" minOccurs="1" maxOccurs="1"/>
      <anyElement minOccurs="1" maxOccurs="1" require="http://relaxng.org/ns/compatibility/annotations/1.0 http://relaxng.org/ns/structure/1.0"/>
    </alternate>
  </content>
~~~

**Review by martindholmes — COMMENTED** [review]
This looks fine to me. If all tests pass, good to merge.

**Comment by ebeshero** [comment]
Yes--it looks exactly as we planned! I have not pulled it in to test yet...

**Review by ebeshero — APPROVED** [review]
I've just run tests and built things, and see no problems here. :-)

**Pull request merged**
