### PR TITLE
Issue 2400 gender to cast item part

### PR DESCRIPTION
**Pull request by ebeshero**
This adds `@gender` as an option to members of model.castItemPart (for `<actor>` and `<role>`), as we originally intended. Additionally it adds `@sex` to `<actor>` so both are available.

### CODE REVIEW

**Review by sydb — APPROVED** [review]
Changes to .xml files look good to me.
I built the _Guidelines_ in this branch, no errors.
I looked at the resulting ref-role.html file, looked OK.
I do not grok the .yml file changes.

**Comment by sydb** [comment]
I realize we are technically in freeze, but this PR is labeled high priority and GO. I have just tried the following in my local repo[1]:

- updated
- merged release-4.6.0 into issue-2400-gender-to-castItemPart
- make clean validate html-web test exemplars

No unexpected errors, and the result looks quite reasonable to me.

Can we consider merging this into upcoming release?

[1] Note-to-self: Padfoot:~/Documents/TEI_gitHub/

**Comment by joeytakeda** [comment]
>  I do not grok the .yml file changes.

Those were from #2399, so no problems there

And all of the rest of the changes look good to me, too! Thanks @ebeshero and @JanelleJenstad for your work on this—

In terms of merging in, should it go into `dev` then the release branch? Or should this PR be closed, and a PR be raised for merging into `release-4.6.0` (I believe that would also re-build the specList and make it not be in conflict)

**Comment by ebeshero** [comment]
Hi all! I opened the PR, so I shouldn't pull it in. :-) I think this one is important for the current release as it was a piece of unfinished work on the sex and gender tickets we thought we completed in the last release. Can someone kindly merge to the release branch?

**Comment by ebeshero** [comment]
Just corrected my comment--please merge to both the release branch and to dev, I think.

**Comment by ebeshero** [comment]
Do you want me to open a new PR for the release branch?

**Comment by sydb** [comment]
Good question, @joeytakeda. The short answer is I have no idea. I do not know how to create a pull request to ask for merging into release-4.6.0 branch, either, though.

As a general rule, we do not want to merge things intended for the release into dev during freeze, because someone might have committed something that is not supposed to go into the release into dev. However, we could check and see, and if nothing has been committed since I created new 4.6.0 branch this morning, just cheat. (I don’t like it, but I like it more than waiting until next release for these changes!)

**Pull request merged**
