### PR TITLE
Revising definition of desc, adding model descLike per #1967

### PR DESCRIPTION
**Pull request by MegJBrown**

### CODE REVIEW

**Review by martindholmes — APPROVED** [review]
This all looks good to me.

**Comment by sydb** [comment]
Thanks, @martindholmes. The main issue, in my mind, is the prose description of `<desc>` itself.

**Comment by martindholmes** [comment]
> Thanks, @martindholmes. The main issue, in my mind, is the prose description of `<desc>` itself.

@sydb I presumed that had been agreed on by Council during discussions. Not so?

**Comment by sydb** [comment]
Oh, no. @MegJBrown and I made that definition up, and are not convinced we have it right. (And you may notice there is an alternate as a comment.)

**Comment by martindholmes** [comment]
@sydb @MegJBrown I think the definition is solid. And actually I think the element name does 90% of the work anyway. :-)

**Review by JanelleJenstad — APPROVED** [review]

**Comment by JanelleJenstad** [comment]
Looks good to me! Thanks Meg!

**Comment by JanelleJenstad** [comment]
Leaving it to @MegJBrown to merge. Would you please let me know when you are going to do it? I could use a bit of a tutorial.

**Comment by ebeshero** [comment]
@JanelleJenstad The protocol we’ve been observing is that someone other than the pull requester presses the green button to merge. It’s okay to do it if you approve!

**Comment by JanelleJenstad** [comment]
> @JanelleJenstad The protocol we’ve been observing is that someone other than the pull requester presses the green button to merge. It’s okay to do it if you approve!
Done! I wasn't expecting it to be that easy! What about deleting the branch? Should I press the "Delete branch" button or is that Meg's job?

**Comment by ebeshero** [comment]
@JanelleJenstad Yes, I think deleting the branch following the pull request is usually the pull-requestor's job, though I don't know if we're always good about it. Eventually we'll "prune" the excess branches.

**Pull request merged**
