### PR TITLE
add `@xml:id`s to `<figure>`, `<table>`, and `<egXML>` elements

### PR DESCRIPTION
**Pull request by sydb**
Added an `@xml:id` attribute to every `<figure>`, `<table>`, and `<egXML>` element that did not already have one.

ID format (decided upon at Council F2F in Buenos Aires) is
1. the `@xml:id` of the nearest ancestor that has an `@xml:id`
2. a hyphen
3. the GI of the current element
4. a hyphen
5. a two-character disamiguator ([a-z][a-z]).
This (I think) completes the first step of #1881.

### CODE REVIEW

**Comment by sydb** [comment]
OK, I have just spent a couple of hours merging dev into this branch so that it can be merged back automagically. If we could review it and get it merged before that has to happen again, that would be good.
Passes all tests in the docker on my work machine.

**Review by ebeshero — APPROVED** [review]
@sabineseifert @torstenroeder You did some seriously patient and persistent work with @sydb to finish this massive xml:id task! Thank you on behalf of all of us on Council who weren't there to help!

**Comment by ebeshero** [comment]
I'm *almost* ready to merge this, except it's failing `make validate` for me on my local tests with an error on nvdl. I think this might be harmless or something distinct to my local setup--but I'd like someone else to test the branch before we merge, or remind me what's up with the nvdl test?

**Comment by ebeshero** [comment]
@joeytakeda I remember / Slack concurs that we were exploring this nvdl issue in testing earlier this summer...

**Comment by ebeshero** [comment]
Never mind--false alarm! @sydb pointed out that wasn't a real error message after all in `make validate`. Merging now...

**Pull request merged**
