### PR TITLE
Added stage to att.written

### LINKED ISSUE #2197: Add <stage> to att.written
The @hand attribute (att.written) is intended to "indicate the hand in which the content of an element was written in the source being transcribed." For transcriptions [originally, I wrote "sourceDoc-like transcriptions," which was misleading] members of att.written include att.transcriptional elements such as `add`, `del`, `subst` and so on; for correspondence, structural elements such as `postscript`, `salute`, and `signed` are members. But although manuscripts of dramatic texts are often the work of multiple scribes, none of the elements commonly used in drama encoding are members of att.written. We would like to see at least `stage`added to att.written to handle the most straightforward cases of MS dramas written in multiple hands. (We would welcome use cases of `sp`, `speaker`, `head`, `lg` and `l` being written in a second hand but haven't stumbled across any examples in the corpus yet.)

It would be useful generally (not just to us) to have the hand attribute on `stage` in particular because stage directions are frequently added in another hand: by the bookkeeper using an authorial ms as a prompt copy, by a copyist after seeing a play in performance, by a director making notes, and by stage managers who record actual performance actions. In other words, `stage` is a structural element that often functions in a stand-off sort of way.

USE CASE 1:
The Douai Manuscript MS787 is described by Line Cottegnies, the lead of the Douai Shakespeare project, in the journal of la Société Française Shakespeare (SFS): https://journals.openedition.org/shakespeare/4289.

See especially the image at https://journals.openedition.org/shakespeare/docannexe/image/4289/img-2.jpg, where one can see the stage direction [Enter Romeo written in the right margin in a different hand.

USE CASE 2:
In this leaf from the ms of Sir Thomas More, a play written in at least four different hands by different authors (including Shakespeare), the stage direction "Enter Fishmonger" is written in a different hand and enclosed in a rhomboid.

STM_SD

Douai_RomSD

.

### PR DESCRIPTION
**Pull request by JanelleJenstad**
We need to test this.

### CODE REVIEW

**Review by martindholmes — COMMENTED** [review]
This looks good to me. Tests seem to be passing.

**Comment by ebeshero** [comment]
@JanelleJenstad This looks perfect to me! I've tested it locally and it looks good in the Spec page when we build it.

**Review by ebeshero — APPROVED** [review]
@JanelleJenstad This looks perfect to me! I've tested it locally and it looks good in the Spec page when we build it.

**Comment by ebeshero** [comment]
@raffazizzi Can you take a look at this and merge in the PR for the release if you approve? This should help wrap up #2197.
Next steps (after this release): @JanelleJenstad and I will open a new ticket to call for examples using `att.written` on `<stage>` for the Guidelines Drama chapter.

**Comment by ebeshero** [comment]
Bump @raffazizzi or @hcayless  : We'd like to get this in the next release.

**Comment by martinascholger** [comment]
Tested, looks good to me.

**Pull request merged**
