### PR TITLE
update copyright notice

### PR DESCRIPTION
**Pull request by sydb**
Per #2514, updated the copyright notice to a shorter comment that fits on 1 line in the Source/Specs/\*.xml, Source/Guidelines/en/\*.xml, and Source/Guidelines/fr/HD-Header.xml files.

For a detailed discussion of what I did, see post on the issue itself.

### CODE REVIEW

**Review by ebeshero — APPROVED** [review]
Looks good for removing the extra line breaks and notation, short of reducing the slightly repetitive wording itself.

**Review by trishaoconnor — COMMENTED** [review]
The changes look good to me. The updated copyright is more concise and it looks tidier having the notice on one line.

**Comment by sydb** [comment]
@ebeshero — Feel free to change to or suggest different wording. Now that it is a completely consistent string all on one line, it is trivial to change. (I would use Perl, but sed, awk, or any good text editor like oXygen, BBEdit, Emacs, vim, or Sublime, could do this easily.)

**Comment by ebeshero** [comment]
I double-checked the British English spelling of verb (license) and noun (licence), and it's all fine. Glad you put back the XML declaration (and found more such to missing lines to address).

**Pull request merged**
