### PR TITLE
Update reg.xml

### PR DESCRIPTION
**Pull request by knagasaki**

### CODE REVIEW

**Review by martindholmes — COMMENTED** [review]
cit.xml では「引用内容」というglossについてなんですけど：普通の使い方では`<cit>`は引用として子要素の`<quote>`は引用の内容を示すではありませんか。
cl.xmlの<remarks>では、"relative clause"というのは「連体修飾」より「関係節」をよく見たことがありますが、「連体修飾」でもいいかもしれません。
僕は誤解や間違いしてしまってごめんなさい。

**Comment by tuurma** [comment]
@knagasaki f2f subgroup cannot judge the merit of Martin's suggestions, would you like to respond to them and should we treat this PR as a Work in Progress or shall we try to merge it as soon as possible and further amendments and extensions can be brought in as a separate PR.

**Comment by tuurma** [comment]
@knagasaki apart from the main body of the contributions, current version seems to be conflicting with the dev branch, if you could try to resolve these, it would be easier to merge for us

**Comment by martindholmes** [comment]
@tuurma My comments are just queries about two vocabulary choices, and shouldn't be viewed as blocking if you need to get this merged before a release; I may not actually know what I'm talking about. :-)

**Comment by tuurma** [comment]
This is what we assumed, that vocabulary adjustments should not block the progress made already. Resolving merge conflicts though would be very helpful. Though these seem pretty straightforward, so person merging can probably do it too.

**Comment by knagasaki** [comment]
> cit.xml では「引用内容」というglossについてなんですけど：普通の使い方では`<cit>`は引用として子要素の`<quote>`は引用の内容を示すではありませんか。 cl.xmlのでは、"relative clause"というのは「連体修飾」より「関係節」をよく見たことがありますが、「連体修飾」でもいいかもしれません。 僕は誤解や間違いしてしまってごめんなさい。

I'm sorry for my late reply. Thank you for checking the translations.
Our thoughts on the two points are:
1. 「引用内容」in cit.xml attempts to translate "cited quotation" in English. 
2. In cl.xml, as「連体修飾」 is more general than 「関係節」, some linguists in the translation team selected the word.

**Comment by ebeshero** [comment]
Council at VF2F asks @tuurma to update this branch, as she can easily resolve the conflict and merge.

**Pull request merged**
