### PR TITLE
Build tweaks related to testing

### PR DESCRIPTION
**Pull request by duncdrum**
when running `make test` the detest.log is immediately removed, making it impossible to inspect or keep for moving into `expected-results` this will clean only temporary files when running `test`.

`make clean` will delete `detest.log` as usual.

see #1898

### CODE REVIEW

**Comment by duncdrum** [comment]
any takers? I d really like to get this merged so my CPU can spend more time doing useful things while working on uniHan ;-)

**Comment by sydb** [comment]
Will try to test now …

**Comment by sydb** [comment]
Sorry for the delay. I ran a full local build of both the dev branch and your fork, @duncdrum. I would love to be able to report that they both worked. But the opposite was the case: neither build succeeded.

The problem **may** be something in my local environment, but I am too tired to check into that now. Will try to do so in the morning.

P.S. On _reading_ the changes you made, they all seem perfectly sane to me.

**Comment by duncdrum** [comment]
hmm that is strange did you test of dev include 8c67de23c612248f399962451100fd9de1dc812c ? that is failing on travis too. 
This feature branch is passing both on travis and locally, what error message do you get?

**Comment by sydb** [comment]
False alarm @duncdrum. Failure was only in dev, not in yours. Trying again …

**Comment by sydb** [comment]
P.S. Yes, failure in dev was caused by that confounding commit. Hoping to look at that in ~4 hours.

**Comment by sydb** [comment]
I repeated my experiment, correctly this time. While there are some minor differences in the output, all except the fact that one build had more “Warning: XML resolver not found; external catalogs will be ignored” messages than the other are easily explained by changes that had been made to dev.

**Pull request merged**
