### PR TITLE
Schematron refinements:

### PR DESCRIPTION
**Pull request by rvdb**
-refined end-punctuation checks for footnotes and bibliography
  -added check for non-breaking space characters

### CODE REVIEW

**Comment by rvdb** [comment]
@martindholmes Should I do anything to make the test pass?

**Comment by martindholmes** [comment]
@rvdb Could you merge dev into your branch and try again? A lot has changed on the main repo.

**Comment by rvdb** [comment]
@martindholmes Weird, I thought I had tried to make sure everything was up-to-date before my first commit (Git Is Terrific, but I'm probably repeating myself). I hope I've merged the right things now; a couple of commit messages have been added, but the changed files list is looking good: only my changes to the ODD file are listed.

**Comment by martindholmes** [comment]
Merged! Thanks indeed.

Git is indeed Terrific. :-)

Cheers,
Martin

**Pull request merged**
