### PR TITLE
Issue 2106: broken links to non-English bibliography entries

### PR DESCRIPTION
**Pull request by HelenaSabel**
PR to tackle issue #2106.

The decided solution is to merge the two language-specific `<listBibl>` (French and Taiwanese Mandarin) into the main `<listBibl>` of the examples. 

One of the assigned tasks was to verify whether there were any cases of the same bibliographic work in two different languages. This was not the case, but I did encounter a reference to the same work (in the same language) that entails two different `<biblScope>` elements and thus is encoded as two independent `<bibl>` elements; see [entries 166 and 167 in the current release of the Guidelines](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/BIB.html). If this is the decided criterion, it would make sense that for different languages, two different entries are created which means that merging these `<listBibl>` was even less problematic than originally thought.

Thus, the main difficulty of the merge is the ordering of the new `<listBibl>`. The encoding of the bibliographic references is not consistent, which complicates matters. However, my main doubt is how to deal with alphabetic ordering of non-Latin script languages. I am only familiar with Latin and Greek scripts and the convention I know is to order first the Latin script and then the Greek one. However, by looking at the current release, I see that entries 208 and 295 have specific positions which makes me think that there might be a different criterion at play other than just ordering the scripts individually. Maybe one of the Japanese-speaker colleagues (@knagasaki ?) could confirm that the order of Japanese entries in the [current release](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/BIB.html) is the expected one? 

The Taiwanese mandarin entries were ordered in their own block, but with the merging of the lists, I also wonder what their optimal location is.

### CODE REVIEW

**Comment by knagasaki** [comment]
> 

Thank you for confirming it.
In the alphabetic ordering based on pronounciation,
No. 208 (Author: Osumi, Akiko) is put on an appropriate place.
However, the author name of the No. 295 is "Sakiyama, Osamu" (not Zakiyama). So, move it to No. 232 or so.

**Comment by HelenaSabel** [comment]
Thank you very much, @knagasaki!

**Comment by sydb** [comment]
I strongly suspect that the duplication of the bibliographic entries for examples taken form Terry’s book (166 & 167) is attributable to two different authors writing those parts of the _Guidelines_. In any case, seems pretty clear to me that either

1. The entire work should be cited (like 167, but not scoped to just page 1), and both examples should point to the one entry that cites it; OR
2. The specific spot in the work should be cited in both cases (i.e., put more info into 167 to make it like 166 — probably requires someone finding a physical copy of the book or getting PDF, e.g. from [researchgate](https://www.researchgate.net/publication/230876242_The_Vastness_of_Natural_Languages); I believe the 1984 edition has ISBN 0631134611.)

**Comment by HelenaSabel** [comment]
I added the “Needs discussion” label because I am not familiar with the right convention to order the Taiwanese mandarin entries. 1) Should they be their “own block” or 2) should they be ordered based on pronunciation like for Japanese?

**Comment by sydb** [comment]
I do not know, @HelenaSabel, but @mbingenheimer (Marcus Bingenheimer <bingenheimer@temple.edu>), @cwittern (Christian Wittern <cwittern@gmail.com>), and @acmuller (Charles Muller <acmuller@l.u-tokyo.ac.jp>) would be the first people I would ask.

**Comment by 747** [comment]
@HelenaSabel 

> ... 1) Should they be their “own block” or 2) should they be ordered based on pronunciation like for Japanese?

Since Taiwan does not have an agreed phonetic representation of Chinese words, a Han script author-year bibliography is sorted on author's name (surname first) by stroke count and stroke type (much the same way as the Beijing Olympics ordering, but need to follow the Taiwanese stroke order). As a result, Japanese (and maybe Korean) literature is mergeable, but characters should be transcribed into the Traditional variant. The Han and alphabetical bibliographies thus must be kept in separate blocks, and the former comes first.

**Comment by HelenaSabel** [comment]
@JanelleJenstad @bleekere @ebeshero I’ve merged the bibliographies following the discussion we had in the TEIC meeting.  I am sure there are errors in the sorting, but at least this fixes the broken links problem (which was the main issue).

I’ve tried to correct some inconsistencies of the bibliographic references, but this would be a completely new ticket and would need a thorough review with a predefined template for bibliographic citations. In any case, you will notice that there are changes in the `Specs` because there were some entries that were repeated (but with different IDs) thus I included a single entry and then corrected the URIs accordingly.

**Review by JanelleJenstad — APPROVED** [review]
Thanks for doing all this work! We'll need to make a note to check sorting after the relesease.

**Review by ebeshero — APPROVED** [review]
Any and all repairs to the confounding BIB are welcome, and there will always be more to correct. Thank you for your systematic care with this, @HelenaSabel!

**Comment by ebeshero** [comment]
I'm taking the liberty of accepting this PR in the interests of time, as the clock is ticking for the upcoming release and it's a holiday weekend.

**Pull request merged**
