### PR TITLE
move q to model.hiLike (option 1)

### PR DESCRIPTION
**Pull request by peterstadler**
This PR investigates *an* option to implement #1918. It consists of three steps (= commits):

1. make `<q>` a member of `model.hiLike` and remove its membership of `model.qLike`
2. rename `model.qLike` -> `model.attributable` (since `<q>` is not member of this class anymore)
3. add `<q>` to missing contexts (since `model.qLike` was allowed in additional contexts)

The result should (technically) work and allow for `<q>` to appear in these additional contexts, accomplishing the outstanding issues #1858 and  #1658:

* analysis: m, span, w 
* core: bibl, date, resp, time 
* corpus: activity, channel, constitution, derivation, domain, factuality, interaction, locale, preparedness, purpose 
* dictionaries: re, sense 
* drama: castItem 
* figures: formula 
* header: authority, catDesc, classCode, creation, funder, language, principal, sponsor 
* msdescription: collection, institution, origDate, repository 
* namesdates: age, langKnown 
* tagdocs: valDesc 
* textcrit: witDetail 
* textstructure: byline, closer, dateline, docImprint, opener 
* transcr: line, zone 
* verse: metSym

### CODE REVIEW

**Comment by ebeshero** [comment]
@sydb I am happy to draft a new description for `att.attributable` and add it to the pull request in the next few days (still unpacking computers during the move).

**Comment by ebeshero** [comment]
@peterstadler @sydb : I just pushed up a new desc for `model.attributable`: "groups elements that contain a word or phrase that can be attributed to someone." How does that look? NOTE: we need to deal with the descs in other languages. I left those alone in this commit but we should either remove them or ask for help in changing them.

**Comment by sydb** [comment]
Thanks, @ebeshero! Not sure I like the word “someone”, though. The word or phrase might be attributed to an organization (“Neither snow nor rain nor heat nor gloom of night stays these couriers from the swift completion of their appointed rounds”), a diety (“Thou shalt not kill”), a pair of people (“Yesterday — all my troubles seemed so far away”; “Be excellent to each other”), an android (“Sir, the possibility of successfully navigating an asteroid field is approximately 3,720 to 1.”; “Zero-point-six-eight seconds, sir. For an android, that is nearly an eternity.”), a computer (“I’m sorry Dave, I’m afraid I can’t do that”), or an alien (“When 900 years you have reached, look as good you will not!”).

Also note that as long as the `@versionDate` attribute is updated appropriately, we do not need to re-write the `<desc>` in other languages in order to fix this and close the ticket. It is well understood and well the case that translations are often out of date. (That said, we may prefer to nuke the ones to which we cannot provide a translation in a case as drastic as this.)

**Comment by ebeshero** [comment]
@sydb Can “someone” refer to an organization as well as a person in the context of attribution? Would “some authority” be a better solution?

**Comment by ebeshero** [comment]
@sydb I think we had better delete the outdated translations in other languages. But this is probably an easy one to get fresh translations quickly, so maybe we can just call for some help on the ticket.

**Comment by sydb** [comment]
I think “someone” could be used for an android or alien, and maybe a computer or a pair of people, but a bit of a stretch for an organization, and I am sure there is fervent disagreement among religions about deities, an argument we’d like to steer clear of.
So yes, I like “some authority” or “an external agency” or some such better.

**Comment by ebeshero** [comment]
@sydb Agreed—I shall push up a revision with this phrasing, in which I also comment out the translations...

**Comment by ebeshero** [comment]
@peterstadler @sydb I've modified the phrasing to "some authority" because the authority could, after all, be oneself (making "external" to limiting). I hope this is sufficiently wide-ranging. I've also commented out the old translations for model.qLike, and would like to call for people to update them, but perhaps after this is merged to `dev`?

**Comment by sydb** [comment]
OK. I am still a little wishy-washy on that description, @ebeshero, but I can’t think of anything better at the moment, so I think we should go with it. (My concern, BTW, is that someone is going to, perhaps appropriately, say “I want to quote him, but he is by no means an _authority_.”.)

However, @peterstadler, there is another minor problem, here. IMHO the link from the model.attributable tagdoc (i.e., the `<listRef>` in model.attributable.xml), if present at all, should not point to 3.3, but rather to 3.3.3 and perhaps 4.3.2. (I.e., not `#COHQ`, but rather `#COHQQ` and maybe `#DSFLT`.)

**Comment by peterstadler** [comment]
I added a Jenkins job for this PR (branch) for facilitating the review process: https://jenkins.tei-c.org/job/TEIP5-branch-issue-1918a/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/index.html
@ebeshero @sydb what do you think: does it look good to be included in this release?

**Comment by ebeshero** [comment]
Before I make another commit to this PR, I'm noting one of the Travis checks isn't passing. Is that a real issue, or not? Should I wait for a correction before adding a commit? @peterstadler @sydb

**Comment by ebeshero** [comment]
While I'm waiting to hear about the failed test, here is the simple change I propose to address @sydb 's concern. Currently in the PR, the phrasing we have for the new model.attributable is:
```
model.attributable groups elements that contain a word or phrase that can be attributed to some authority.
```
If I understand correctly, @sydb is not sure that attributed statements always derive from authorities. So my proposal is to change "authority" to "agent" thus:

```
model.attributable groups elements that contain a word or phrase that can be attributed to some agent.
```

Other words that might serve could be "agency" or "entity". Thoughts?

Note: In my edits I'm sticking with "some" as a modifier because it's ambiguous enough that it refer to oneself or others, and I want to make sure that we preserve the possibility of self-attribution even if it's understated or implied by the language.

**Comment by peterstadler** [comment]
@ebeshero I just brought this PR up to date with dev which should fix the failing tests.

**Comment by ebeshero** [comment]
@peterstadler @sydb  I've just pushed some new phrasing for model.attributable:
```
<desc versionDate="2020-08-05" xml:lang="en">groups elements that contain a word or phrase that can be attributed to some source.</desc>
```
I don't know why the word "source" didn't occur to us before, but I liked it better than "authority" or "agent" in the end, and it can be self-referential, and doesn't get into other issues. A source can be any kind of entity, an organization or an individual. Will this phrasing work for us? 

I think if this answers @sydb 's concern, we'll be ready for review of the branch by @MegJBrown and @npcole .

**Comment by MegJBrown** [comment]
Just noting that the language discussed here sounds good to me (and I do like "source" better than "agent" or "authority"). I'm afraid I'm not the one to supply translations (unless you'd like very possibly wrong ones).

**Comment by sydb** [comment]
That’s better, @ebeshero, thanks. Would “… could be attributed to a particular source” be even better?

**Comment by ebeshero** [comment]
@sydb On the off chance that a source is not very particular, how about we simplify it a little more to say “... could be attributed to a source”?

**Comment by ebeshero** [comment]
@sydb @peterstadler  I've made that small change to the wording. @martinascholger : I don't understand why our labeling on this pull request is still "Needs Discussion" when it also has a Release Milestone. Shouldn't this just be Green now? Are we satisfied that discussion is now concluded, and are we ready to merge this branch to dev for the release?

Note that we are lacking any non-English descriptions of model.attributable, but I think we could easily supply one or two as long as we are now satisfied with its wording.

**Comment by peterstadler** [comment]
I assigned @martinascholger (and marked it as green) to have a final look at it and then push the button. Syd's concerns have been addressed by @ebeshero and agreed on by @MegJBrown so I really think this is good to go :) 

Non-English descriptions have to be added later.

**Comment by martinascholger** [comment]
looks good to me, also tested in oXygen. @peterstadler in the German translation you have added "externen" (external) in parenthesis. Should this also be added to the English version?

**Comment by ebeshero** [comment]
@martinascholger @peterstadler I don’t think the word “external” should be added to the English description. Is it needed in the German? (My German isn’t good enough to be sure of how it is being applied here, but as long as the intention is to cite or attribute a word or phrase to a source, I think it does not matter whether that source is internal or external.)

**Comment by sydb** [comment]
I agree with @ebeshero, it would be bad to preclude the possibility that the phrase in question is attributable to an internal source. (I’m thinking of the “remember what I told you” phone conversation between Dr. Richard Kimble (Harrison Ford) and Sr. Deputy Marshal Samuel Gerard (Tommy Lee Jones) in _The Fugitive_.)

We could say “attributable to a source, whether internal to the text or external” or some such, but I am not sure we gain much from it.

**Comment by ebeshero** [comment]
I think we should keep this as simple as possible, so I'm not in favor of adding more words at this point.

**Comment by peterstadler** [comment]
I totally agree with the native speakers not to alter the English description. Yet, translating to German, I found it hard to go without the parenthesis. But that's just my Sprachgefühl, I wonder what @martinascholger thinks? 
[If that's a show stopper now, we better remove the translation and merge this PR without it.]

**Comment by martinascholger** [comment]
Definitely not a show stopper. I would have left out the parenthesis, though. I'll merge this tomorrow.

**Pull request merged**
