### PR TITLE
p5odds: Allow "URN" as value of `@type` of `<idno>`

### PR DESCRIPTION
**Pull request by sydb**
Per Slack conversation with @raffazizzi , add "URN" as possible value to `@type` of `<idno>` in p5odds. While I was there I also:

- Changed "url" to "URL"
- Added "URI"
- Updated glosses & descriptions a bit

I have checked. Use of `<idno type="URN">` results in output that is not really pretty in the HTML _Guidelines_ (specifically, in the Bibliography), but not particularly ugly, either, and does not falsely imply that your web browser will open a URN. (Which use of `<ptr target="urn:duck:billed:platypus"/>` would.)

I have also checked, and there were no occurrences of `<idno type="url">` in P5, so changing this to "URL" should not cause problems.

### CODE REVIEW

**Comment by sydb** [comment]
Note: I am not sure the “TEI: ODD” label is correctly applied to this — it might be for the TEI language defined _by_ the Guidelines, not the TEI language defined _for_ the Guidelines. Sigh. Anyway, this is high priority because it is holding up work on https://github.com/TEIC/TEI/issues/2516.

**Review by joeytakeda — COMMENTED** [review]
All tests pass and the changes seem reasonable to me.

**Review by martindholmes — APPROVED** [review]
Looks good. Upper case for URL brings it in line with the others in P5.

**Comment by ebeshero** [comment]
I've tested and built guidelines and exemplars with it. All good, and the update is definitely useful in the cause of new and wider-ranging examples of `<idno>` for the Guidelines. As it's an urgent PR holding up other tickets, I'm merging it now.

**Pull request merged**
