### PR TITLE
Ebb schematron explan2

### PR DESCRIPTION
**Pull request by ebeshero**
This branch is a rebased version containing some work we did on #1621 to the Use chapter. Since I just rebased the branch and we had some trouble with this a while ago, I'd like to get Jenkins / Travis to validate it before we merge to dev.

### CODE REVIEW

**Comment by peterstadler** [comment]
For convenience, I added a Jenkins job for this branch: https://jenkins.tei-c.org/job/TEIP5-branch-ebb_SchematronExplan2/

**Comment by ebeshero** [comment]
@peterstadler Thanks! I've just deleted those two DTD and Schema directories that were old local build artifacts.

**Comment by peterstadler** [comment]
Sorry to have been imprecise, but it's not just those two folders (DTD and schemas) but all sorts of other stuff. Best to do a `make clean` to remove those build artifacts completely.

**Comment by ebeshero** [comment]
Aha! I see an unfinished element flagged--repairing...

**Comment by ebeshero** [comment]
Yikes-- I see that now--sorry. Cleaning...

**Comment by ebeshero** [comment]
@peterstadler and all: Looks like this branch has now passed, so perhaps we can fold it in to dev?
There was a mysterious error on one of the egXML elements that we modified on this branch.  In USE at MDNS in the `<egXML>` in `p[3]`, we were showing how to create a custom attribute in a new namespace on an existing TEI element. On this egXML, the `@valid` attribute was mysteriously set to "false", rendering it pink and looking like it was an example of a mistake when it's a legitimate example, so we changed it on this branch to "true"--and that breaks the build with this error:
```
/var/tei/P5/valid/TEI_1-text_1-body_1-div_USE-div_MD-div_MDNS-p_3-egXML_1-:6:50: error: unfinished element
```
The error points to the `<egXML>` in lines 607 - 615 in USE: 

``xml
<egXML source="#NONE" xmlns="http://www.tei-c.org/ns/Examples" rend="full" valid="true">
	  <elementSpec ident="p" mode="change">
            <attList>
              <attDef ident="topic" mode="add" ns="http://www.example.org/ns/nonTEI">
                <desc>indicates the topic of a TEI paragraph</desc>
                <datatype></datatype>
              </attDef>
            </attList>
          </elementSpec></egXML>
``
I changed this back to `valid="false"` (its original state) and that repaired the build, but it leaves me unsatisfied because I don't think we want to convey that this is an invalid use case. Any thoughts? I wrote a little explanation after the egXML: "(Note that this example looks as if it is invalid in on this page because in fragmented form here it represents a customization that is not connected to a complete ODD.)". I'm not sure whether that's quite the correct explanation, however, and I'd rather we could just render this as a proper egXML and not an invalid one.

**Comment by lb42** [comment]
It's invalid or fragmentary...data type can't be empty

**Comment by ebeshero** [comment]
Thanks @lb42 ! That passed the checks. let me update the branch one more time from dev...

**Comment by ebeshero** [comment]
And, there's nothing new to pull in, and all checks have passed. So, would someone here merge this to dev? Thanks, @lb and @peterstadler for the help!

**Comment by peterstadler** [comment]
NB: the P5 build ist still broken so be warned that Jenkins may complain …

**Comment by ebeshero** [comment]
@peterstadler I was watching the Travis checks, and I'm just looking in on [Jenkins](https://jenkins.tei-c.org/job/TEIP5-branch-ebb_SchematronExplan2/lastFailedBuild/parsed_console/) now:  
Looks like tei_simpleprint.dtd is missing, and the major error seems to be 
```
fatal: file not found: /var/jenkins_home/workspace/TEIP5-branch-ebb_SchematronExplan2/P5/Exemplars/tei_simplePrint.nvdl (No such file or directory)
``` 
I am pretty sure we didn't touch anything in Exemplars on this branch. I'm hoping that merging to dev will take care of the missing .nvdl file issue. . . Keeping an eye on it.

**Comment by ebeshero** [comment]
Aha! I see this is coming from [build number 247](https://jenkins.tei-c.org/job/TEIP5-dev/), which I'd have merged into my branch while rebasing. Okay, it's probably safe to delete this ancient branch, then.

**Comment by ebeshero** [comment]
Is there any reason to keep this branch until the Jenkins build is restored? Or best to delete it now?

**Comment by peterstadler** [comment]
yes, you can (should) delete it once it's merged

**Pull request merged**
