### PR TITLE
multiple ruby annotations with same alignment

### PR DESCRIPTION
**Pull request by martinascholger**
example added demonstrating the parallel approach, for #2110. An example for the nested approach is still needed.

### CODE REVIEW

**Review by martindholmes — COMMENTED** [review]
There's a comma splice here:

The first of the two <gi>rt</gi> elements would appear to the right of the ruby base (<gi>rb</gi>), the second would appear...

I would suggest '..., while the second would appear'.

The xml:id="B" collides with an id in the TC chapter, so perhaps it could be made unique by adding a prefix "ancB".

**Comment by martinascholger** [comment]
@raffazizzi , @martindholmes can you please have a look at this PR

**Review by martindholmes — APPROVED** [review]
Looks good to me.

**Comment by HelenaSabel** [comment]
It looks good to me to so I proceed to merge it (without waiting for a second review)

**Pull request merged**
