### PR TITLE
rename unboundedInt to unboundedCount

### PR DESCRIPTION
**Pull request by sydb**
Per #2327.
I also changed the description of the datatype while I was there. That change and whitespace changes were checked in separately to try to make it easier on reviewers.

### CODE REVIEW

**Comment by martindholmes** [comment]
@sydb Looks like the PR branch needs to be brought up to date from dev, no? Also, what are the implications for Stylesheets? Should I create a test build on Jenkins?

**Comment by sydb** [comment]
Okey dokey.
On it.
Sigh.

**Comment by sydb** [comment]
Done, but I have not tested myself, yet.

**Review by ebeshero — APPROVED** [review]
@sydb Once I reviewed why unboundedInt needed to be changed to unboundedCount, it all made sense to me. The changes look good.

**Pull request merged**
